import jsPDF from 'jspdf';
import { AnalysisResult } from '../types';

export const generatePDF = (data: AnalysisResult) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let y = 20;

  const addNewPageIfNeeded = (requiredSpace: number = 30) => {
    if (y + requiredSpace > 280) {
      doc.addPage();
      y = 20;
    }
  };

  const addTitle = (text: string, size: number = 16) => {
    addNewPageIfNeeded(20);
    doc.setFontSize(size);
    doc.setFont('helvetica', 'bold');
    doc.text(text, margin, y);
    y += size * 0.5 + 5;
  };

  const addText = (text: string, size: number = 10) => {
    doc.setFontSize(size);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(text, contentWidth);
    lines.forEach((line: string) => {
      addNewPageIfNeeded(8);
      doc.text(line, margin, y);
      y += 6;
    });
    y += 3;
  };

  // Header
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('ExamStrategy AI Report', margin, 28);
  doc.setTextColor(0, 0, 0);
  y = 55;

  // Overview
  addTitle('Executive Summary');
  addText(data.overview);
  y += 10;

  // Topic Weightage
  addTitle('Topic Weightage Analysis');
  data.weightage.forEach((item) => {
    addNewPageIfNeeded(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`• ${item.topic}`, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.text(`- Frequency: ${item.frequency}% | Trend: ${item.trend}`, margin + 5, y + 6);
    y += 14;
  });
  y += 10;

  // Deep Dive Concepts
  addTitle('Deep Concept Analysis');
  data.deepDive?.forEach((concept, idx) => {
    addNewPageIfNeeded(50);
    doc.setFillColor(248, 250, 252);
    doc.rect(margin - 5, y - 5, contentWidth + 10, 8, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(`${idx + 1}. ${concept.conceptName} (${concept.probability} Probability)`, margin, y);
    y += 12;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    addText(`Examiner Psychology: ${concept.examinerPsychology}`);
    
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    addText(`Predicted Question: ${concept.currentYearPrediction}`);
    doc.setTextColor(0, 0, 0);

    if (concept.occurrences?.length > 0) {
      doc.setFont('helvetica', 'normal');
      addText('Historical Questions:');
      concept.occurrences.slice(0, 3).forEach((occ) => {
        addText(`  [${occ.year}] ${occ.questionSnippet}`);
      });
    }
    y += 8;
  });

  // Sample Paper
  if (data.samplePaper?.length > 0) {
    addNewPageIfNeeded(40);
    addTitle('Predicted Sample Paper 2025');
    const totalMarks = data.samplePaper.reduce((acc, q) => acc + q.marks, 0);
    addText(`Total Marks: ${totalMarks}`);
    y += 5;
    
    data.samplePaper.forEach((q) => {
      addNewPageIfNeeded(20);
      doc.setFont('helvetica', 'bold');
      doc.text(`Q${q.qNo}. [${q.marks} marks] [${q.difficulty}]`, margin, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      const qLines = doc.splitTextToSize(q.text, contentWidth - 10);
      qLines.forEach((line: string) => {
        addNewPageIfNeeded(8);
        doc.text(line, margin + 5, y);
        y += 6;
      });
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`Topic: ${q.topic}`, margin + 5, y);
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      y += 10;
    });
  }

  // Pattern Twists
  if (data.twists?.length > 0) {
    addNewPageIfNeeded(40);
    addTitle('Pattern Twists');
    data.twists.forEach((twist) => {
      addNewPageIfNeeded(30);
      doc.setFont('helvetica', 'bold');
      addText(`Concept: ${twist.originalConcept}`);
      doc.setFont('helvetica', 'normal');
      addText(`Standard: ${twist.standardQuestion}`);
      doc.setTextColor(79, 70, 229);
      addText(`Twisted: ${twist.twistedVariation}`);
      doc.setTextColor(0, 0, 0);
      y += 5;
    });
  }

  // Strategy
  addNewPageIfNeeded(40);
  addTitle('Master Strategy');
  addText(data.strategy);

  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by ExamStrategy AI', margin, 290);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin - 30, 290);

  doc.save('ExamStrategy-AI-Report.pdf');
};
